### ISSUE TITLE
Front end 

### ISSUE THREAD

**Issue by Manraj-Mann** [Manraj-Mann/bitcoding#1]
- [x] Navigation Bar (simple containing home )
- [x]  some styling to table

**Comment by anshikasharmaa1517** [comment]
@Manraj-Mann  Hey there.I would like to work on this issue.

**Comment by Manraj-Mann** [comment]
> @Manraj-Mann Hey there.I would like to work on this issue.

Great you can start working on it , I m assigning the task to you !

**Comment by anshikasharmaa1517** [comment]
ok thanks.

**Comment by Manraj-Mann** [comment]
@awnnshikaa completed the task successfully! Thanks for contributing

**Comment by anshikasharmaa1517** [comment]
Welcome @Manraj-Mann
